---
- name: Install Core Golang Compiler (Arch)
  community.general.pacman:
    name: go
    state: present
  when: ansible_os_family == 'Archlinux'

- name: Install Core Golang Compiler (Debian)
  ansible.builtin.apt:
    name: golang
    state: present
  when: ansible_os_family == 'Debian'
