---
- name: Create bash_aliases file
  ansible.builtin.file:
    path: "/home/{{ username }}/.bash_aliases"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
    modification_time: preserve
    access_time: preserve

- name: Add bash aliases
  ansible.builtin.lineinfile:
    dest: "/home/{{ username }}/.bash_aliases"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    #validate: 'bash -n %s'
  with_items:
    # Better ls
    - regexp: "^alias ll"
      line: "alias ll='ls -al'"
    # One line update.
    - regexp: "^alias update"
      line: "alias update='sudo apt update && sudo apt upgrade && sudo apt autoremove -y && sudo apt clean'"
