---
- name: Full System Upgrade (Debian Based)
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  when: ansible_os_family == 'Debian'

- name: Full System Upgrade (Arch Based)
  community.general.pacman:
    update_cache: true
    upgrade: true
    state: latest
  when: ansible_os_family == 'Archlinux'
